In [1]:
import numpy as np

In [2]:
py_list = [1, 2, 3]
sub_list = [4]

print(py_list * 3)
# print(py_list + 3) # This will not work as it will try to concatenate the list with an integer, which is not allowed in Python.
print(py_list + sub_list)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4]


In [3]:
np_list = np.array([1, 2, 3])
sub_list = np.array([4])
print(np_list * 3)
print(np_list + 3)
print(np_list + sub_list)

[3 6 9]
[4 5 6]
[5 6 7]


Excercise

In [4]:
li = [3, ['3', '4', '5'], 5.5, [4, 5, 6]]

In [5]:
for n, item in enumerate(li):
    print(f"List element {n} is {item} and is of type {type(item)}")

List element 0 is 3 and is of type <class 'int'>
List element 1 is ['3', '4', '5'] and is of type <class 'list'>
List element 2 is 5.5 and is of type <class 'float'>
List element 3 is [4, 5, 6] and is of type <class 'list'>


In [6]:
for n, item in enumerate(li):
    print(f"List element {n} is {item} and is of type {type(item).__name__}")

List element 0 is 3 and is of type int
List element 1 is ['3', '4', '5'] and is of type list
List element 2 is 5.5 and is of type float
List element 3 is [4, 5, 6] and is of type list


In [ ]:
# Other way to get the type of the item
for n, item in enumerate(li):
    print(f"List element {n} is {item} and is of type {str(type(item))[8:-2]}")

List element 0 is 3 and is of type int
List element 1 is ['3', '4', '5'] and is of type list
List element 2 is 5.5 and is of type float
List element 3 is [4, 5, 6] and is of type list
